# Name of website
title: Liferfe - mataparda.net

# Your name to show in the footer
author: Mtp


navbar-links:

  INICIO: "inicio"
  Sonidos:
    - 1980-1990: "XX"
    - 2019-: "XXI"
  Fotografía: "foto"
  Cómic: "espinita"
  Isla:
     - elmalpais: "elmalpais"
     - jardines: "https://jardinedu.github.io/cifpcm/inicio"
  Blog: "/"
  Mtp: "sobremtp"


avatar: "/assets/img/avatar-icon.png"

round-avatar: true

rss-description: This website is a virtual proof that I'm awesome

share-links-active:
  twitter: false
  facebook: false
  linkedin: false
  vk: false
  reddit: false

url-pretty: "mataparda.net"

title-on-all-pages: true

excerpt_length: 5000

feed_show_excerpt: true

feed_show_tags: true

post_search: false

edit_page_button: false

navbar-var-length: false


# Personalize the colours in your website. Colour values can be any valid CSS colour
page-col: "#FFFFFF" 
# blanco
text-col: "#404040" 
# gris medio
link-col: "#4682B4" 
# 4682b4 steelblue
# #008AFF old azul claro
hover-col: "#416787"
# #416787 steel blue 25% mas oscuro
# #0085A1 old azul oscuro
navbar-col: "#EAEAEA"
# navbar-col: "#EAEAEA" OLD gris claro
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#3B3B3B" 
# gris oscuro 3b3b3b
# footer-col: "#EAEAEA" OLD gris claro
footer-text-col: "#FFFFFF"
# footer-text-col: "#777777" OLD gris medio-oscuro
footer-link-col: "799FBF"
# 799fbf steelblue 25% mas claro
# footer-link-col: "#404040" old gris oscuro
# #008AFF old azul claro
footer-hover-col: "#4682B4"
# #4682b4 steelblue
# #0085A1 old azul oscuro

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"




#################################################################################
# --- You don't need to touch anything below here (but you can if you want) --- #
#################################################################################

# Output options (more information on Jekyll's site)
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
